/* eslint-disable no-undef */
/**
 * InternLink's service worker.
 *
 * Written by hand and built with `injectManifest`, rather than generated by
 * Workbox, for one reason: **listener registration order**.
 *
 * Workbox's `generateSW` output wraps everything in an AMD `define()` whose
 * factory runs inside a promise chain, and pulled our push handlers in with a
 * runtime `importScripts('/push-sw.js')` from inside that factory. Both of those
 * are fatal for background push:
 *
 *  - `importScripts()` is only legal during a worker's initial evaluation. Once
 *    evaluation has finished — which it has, by the time a `.then()` callback
 *    runs — WebKit throws. On iOS that meant the `push` listener was never
 *    registered at all, so a notification arriving while the app was closed had
 *    nothing to handle it. Notifications appeared to work only while the app was
 *    open, because that is the one case where the page, not the worker, was
 *    doing the work.
 *  - A push arriving to a stopped worker starts it, evaluates it, then dispatches
 *    the event. Listeners added a microtask later are a race nobody should be
 *    running.
 *
 * So: the notification listeners are registered at the top of this file, in the
 * first synchronous pass, before Workbox is configured. Static `import`s are
 * inlined by the bundler, so there is no `importScripts` at runtime and nothing
 * is deferred.
 */
import { cleanupOutdatedCaches, createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching';
import { NavigationRoute, registerRoute } from 'workbox-routing';
import { CacheFirst, NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

/* ======================================================= notifications === */

const FALLBACK_TITLE = 'InternLink';
const FALLBACK_PATH = '/notifications';

/**
 * Normalises the many shapes a push payload arrives in.
 *
 * FCM nests a data-only send under `data`; a raw Web Push send does not; and a
 * send that carries a `notification` block puts title/body there instead. All
 * three have to work, because which one we get depends on how the message was
 * sent, not on anything this file controls.
 */
function readPayload(event) {
  if (!event.data) return {};

  try {
    const parsed = event.data.json() ?? {};
    return { ...(parsed.notification ?? {}), ...(parsed.data ?? parsed) };
  } catch {
    // Not JSON. Better a notification with only a body than none at all.
    let text = '';
    try {
      text = event.data.text();
    } catch {
      /* nothing readable */
    }
    return text ? { body: text } : {};
  }
}

/**
 * Every push shows a notification. No exceptions, no early returns.
 *
 * A push handler that finishes without calling `showNotification` is a spec
 * violation: Chrome papers over it with a generic "This site has been updated
 * in the background" and both Chrome and Safari revoke the subscription after
 * enough of them. The old handler bailed out whenever `event.data` was empty,
 * which is a slow way to get a device permanently unsubscribed — and the user
 * only finds out by noticing the silence.
 */
async function showPush(event) {
  const payload = readPayload(event);

  const title = payload.title || FALLBACK_TITLE;
  const path = payload.path || payload.click_action || FALLBACK_PATH;
  const tag = payload.tag || undefined;
  const body = payload.body || 'Open InternLink to see what is new.';

  const options = {
    body,
    icon: '/icons/icon-192.png',
    badge: '/icons/icon-64.png',
    // Same tag replaces rather than stacks, so a device coming back online
    // after a gap shows one notification per subject, not twelve.
    tag,
    // `renotify` without a `tag` is a TypeError in Safari, so it is derived
    // from the tag rather than set independently.
    renotify: Boolean(tag),
    timestamp: Date.now(),
    data: { path },
  };

  // Only set when present: iOS ignores `image`, but an explicit `undefined`
  // has tripped up notification constructors before, and `''` is worse.
  if (payload.imageUrl) options.image = payload.imageUrl;

  await self.registration.showNotification(title, options);

  // Best-effort extras. Neither is allowed to keep the notification itself from
  // being shown, which is why they run after the await and swallow failures.
  await Promise.allSettled([
    updateBadge(),
    broadcast({ type: 'push', payload: { title, body, path, tag: tag ?? null } }),
  ]);
}

self.addEventListener('push', (event) => {
  event.waitUntil(showPush(event));
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  event.waitUntil(openApp(event.notification.data?.path || FALLBACK_PATH));
});

/**
 * The browser rotated or expired this device's push subscription.
 *
 * Nothing here can mint a new FCM token — that needs the SDK and a signed-in
 * user, both of which only exist in the page. What it can do is get the
 * browser-level subscription back immediately, and tell any open tab to
 * re-register so the server learns the new token now rather than whenever the
 * user next happens to open the app.
 *
 * Without this handler a rotated subscription meant permanent silence: the
 * device believed notifications were on, the server held a token that no longer
 * routed anywhere, and neither side had any reason to look.
 */
self.addEventListener('pushsubscriptionchange', (event) => {
  event.waitUntil(
    (async () => {
      const key = event.oldSubscription?.options?.applicationServerKey;
      if (key) {
        await self.registration.pushManager
          .subscribe({ userVisibleOnly: true, applicationServerKey: key })
          .catch(() => undefined);
      }
      await broadcast({ type: 'pushsubscriptionchange' });
    })(),
  );
});

self.addEventListener('message', (event) => {
  const type = event.data?.type;
  // Posted by `updateServiceWorker(true)` when the user accepts the update toast.
  if (type === 'SKIP_WAITING') self.skipWaiting();
});

async function windowClients() {
  return self.clients.matchAll({ type: 'window', includeUncontrolled: true });
}

async function broadcast(message) {
  try {
    for (const client of await windowClients()) client.postMessage(message);
  } catch {
    /* No client to tell. The next page load re-syncs anyway. */
  }
}

/**
 * The count on the Home Screen icon, taken from what is currently on screen.
 *
 * Derived from the notifications the browser is already showing rather than
 * from a stored counter: there is no state to drift, and dismissing the
 * notifications drops the badge to match. On iOS this is the only unread signal
 * visible without opening the app.
 */
async function updateBadge() {
  try {
    if (typeof self.navigator?.setAppBadge !== 'function') return;
    const shown = await self.registration.getNotifications();
    await self.navigator.setAppBadge(Math.max(shown.length, 1));
  } catch {
    /* Badging is unsupported on most desktop browsers. Not worth reporting. */
  }
}

/**
 * Focuses the app on the right screen, opening it only if it is not running.
 *
 * The path is handed over by `postMessage` so the SPA router can move without a
 * reload. `client.navigate()` is the obvious alternative and the wrong one here:
 * it is a full document load, and iOS does not implement it at all — a tap would
 * focus the app and then sit on whatever screen it was already showing.
 */
async function openApp(path) {
  const target = new URL(path, self.location.origin).href;
  const clients = await windowClients();

  for (const client of clients) {
    if (!client.url.startsWith(self.location.origin)) continue;

    if ('focus' in client) await client.focus().catch(() => undefined);
    client.postMessage({ type: 'navigate', path });
    return;
  }

  await self.clients.openWindow(target);
}

/* ====================================================== precache/cache === */

precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

/**
 * Control the page as soon as this worker activates.
 *
 * Inside `activate`, not at top level: only the active worker may claim, so a
 * bare `self.clients.claim()` during evaluation rejects with an InvalidStateError
 * on every install.
 *
 * `skipWaiting` is deliberately NOT paired with it — updates stay behind the
 * "new version is ready" prompt so a half-finished profile wizard is never
 * swapped out from under someone. Claiming only matters on first install, where
 * it means push can be enabled without reloading the page first.
 */
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

registerRoute(
  new NavigationRoute(createHandlerBoundToURL('/index.html'), {
    // Never let the SW serve a cached shell for API calls — a stale session
    // payload is worse than an offline error.
    denylist: [/^\/api\//],
  }),
);

registerRoute(
  // Google Fonts stylesheets change rarely; the files never change.
  ({ url }) => url.origin === 'https://fonts.googleapis.com',
  new StaleWhileRevalidate({ cacheName: 'google-fonts-stylesheets' }),
);

registerRoute(
  ({ url }) => url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-files',
    plugins: [
      new ExpirationPlugin({ maxEntries: 20, maxAgeSeconds: 60 * 60 * 24 * 365 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  }),
);

registerRoute(
  /**
   * Cloudinary stills — immutable per URL, safe to cache hard.
   *
   * Video is excluded, and has to be. A `<video>` fetches with Range requests,
   * but `caches.match()` ignores the Range header: every request after the
   * first is answered with the whole cached body, which for cross-origin media
   * is opaque and cannot be sliced. The browser reads that as a server with no
   * range support and ends up with nothing seekable — so the clip streams once,
   * front to back, and then can never rewind. `loop` stops looping and pressing
   * play does nothing, because both of those seek back to the start.
   *
   * Workbox has RangeRequestsPlugin for this, but it needs a readable CORS
   * response to slice, and a 100MB clip has no business in a 200-entry cache
   * regardless. Video goes to the network.
   */
  ({ url }) => url.origin === 'https://res.cloudinary.com' && !url.pathname.includes('/video/'),
  new CacheFirst({
    cacheName: 'cloudinary-media',
    plugins: [
      new ExpirationPlugin({ maxEntries: 200, maxAgeSeconds: 60 * 60 * 24 * 30 }),
      new CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  }),
);

registerRoute(
  // Listing reads are safe to show stale for a moment while the network catches
  // up. Auth and writes are NOT cached at all.
  ({ url, request }) => request.method === 'GET' && /\/v1\/listings/.test(url.pathname),
  new NetworkFirst({
    cacheName: 'api-listings',
    networkTimeoutSeconds: 4,
    plugins: [
      new ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 60 * 10 }),
      new CacheableResponsePlugin({ statuses: [200] }),
    ],
  }),
);
