import { useCallback, useEffect, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { deleteToken, getMessaging, getToken, isSupported, onMessage } from 'firebase/messaging';
import { firebaseApp, isFirebaseConfigured } from '@/lib/firebase';
import { pushApi } from '@/lib/api-endpoints';
import { toast } from '@/lib/stores';

/** Remembered so a granted permission re-registers silently on the next visit. */
const STORAGE_KEY = 'internlink.push.token';

export type PushState =
  | 'unsupported'
  | 'unconfigured'
  | 'denied'
  | 'off'
  | 'enabling'
  | 'on';

/**
 * FR-601 — web push, over Firebase Cloud Messaging.
 *
 * Three things have to line up before a browser will deliver a push: a service
 * worker, a granted Notification permission, and a VAPID key. Any of them
 * missing means the switch must not be offered — a toggle that silently fails
 * is worse than no toggle, which is the same rule the uploaders follow.
 *
 * Permission is only ever requested from a user gesture. A permission prompt on
 * page load is the fastest way to get denied permanently, and `denied` cannot be
 * recovered from in-app: the user has to change it in browser settings.
 */
export function usePushNotifications(): {
  state: PushState;
  enable: () => Promise<void>;
  disable: () => Promise<void>;
  sendTest: () => Promise<void>;
} {
  const [state, setState] = useState<PushState>('off');

  const { data: capabilities } = useQuery({
    queryKey: ['notifications', 'push', 'status'],
    queryFn: pushApi.status,
    staleTime: Infinity,
    retry: false,
  });

  // Resolve the starting state once the environment is known.
  useEffect(() => {
    let cancelled = false;

    void (async () => {
      if (!isFirebaseConfigured || typeof window === 'undefined') {
        if (!cancelled) setState('unsupported');
        return;
      }
      // Safari below 16.4 and every browser in a non-secure context land here.
      if (!('Notification' in window) || !(await isSupported().catch(() => false))) {
        if (!cancelled) setState('unsupported');
        return;
      }
      if (capabilities && !capabilities.available) {
        if (!cancelled) setState('unconfigured');
        return;
      }
      if (cancelled) return;

      if (Notification.permission === 'denied') setState('denied');
      else if (Notification.permission === 'granted' && localStorage.getItem(STORAGE_KEY)) {
        setState('on');
      } else setState('off');
    })();

    return () => {
      cancelled = true;
    };
  }, [capabilities]);

  /**
   * Foreground messages.
   *
   * FCM does not show a notification while the tab is focused — by design,
   * since the user is already looking at the app. Surfacing it as a toast keeps
   * the behaviour consistent without a second system-level popup.
   */
  useEffect(() => {
    if (state !== 'on' || !isFirebaseConfigured) return;

    let unsubscribe: (() => void) | undefined;
    void (async () => {
      if (!(await isSupported().catch(() => false))) return;
      unsubscribe = onMessage(getMessaging(firebaseApp()), (payload) => {
        const data = payload.data ?? {};
        if (data.title) toast.success(data.title, data.body);
      });
    })();

    return () => unsubscribe?.();
  }, [state]);

  const enable = useCallback(async (): Promise<void> => {
    if (!capabilities?.vapidKey) {
      toast.error('Notifications are not available', 'This environment has no push key set up.');
      return;
    }

    setState('enabling');
    try {
      const permission = await Notification.requestPermission();
      if (permission !== 'granted') {
        setState(permission === 'denied' ? 'denied' : 'off');
        return;
      }

      // The PWA service worker (generated by vite-plugin-pwa) is what receives
      // the push, so registration has to be handed to FCM explicitly — the
      // default lookup expects a firebase-messaging-sw.js we do not ship.
      const registration = await navigator.serviceWorker.ready;

      const token = await getToken(getMessaging(firebaseApp()), {
        vapidKey: capabilities.vapidKey,
        serviceWorkerRegistration: registration,
      });

      if (!token) {
        setState('off');
        toast.error('Could not turn on notifications', 'Your browser did not issue a token.');
        return;
      }

      await pushApi.register({
        token,
        platform: 'web',
        userAgent: navigator.userAgent.slice(0, 400),
      });

      localStorage.setItem(STORAGE_KEY, token);
      setState('on');
      toast.success('Notifications are on', 'We will let you know when your network posts.');
    } catch (error) {
      setState('off');
      toast.error(
        'Could not turn on notifications',
        error instanceof Error ? error.message : 'Try again in a moment.',
      );
    }
  }, [capabilities]);

  const disable = useCallback(async (): Promise<void> => {
    const token = localStorage.getItem(STORAGE_KEY);
    localStorage.removeItem(STORAGE_KEY);
    setState('off');

    // Deleting the FCM token first means the browser stops receiving even if
    // the API call fails — the user asked for silence, so silence is what they
    // get regardless of whether our bookkeeping succeeds.
    if (await isSupported().catch(() => false)) {
      await deleteToken(getMessaging(firebaseApp())).catch(() => undefined);
    }
    if (token) await pushApi.unregister(token).catch(() => undefined);
  }, []);

  const sendTest = useCallback(async (): Promise<void> => {
    const result = await pushApi.test().catch(() => null);
    if (!result || result.sent === 0) {
      toast.error('No notification sent', 'This device may not be registered any more.');
      return;
    }
    toast.success('Test sent', `Delivered to ${result.sent} device${result.sent === 1 ? '' : 's'}.`);
  }, []);

  return { state, enable, disable, sendTest };
}
